
const vocab = [
    {latin: "accipere", german: "annehmen, bekommen, empfangen"},
    {latin: "aetas", german: "Zeit, Epoche, (Lebens-)Alter, Generation"},
    {latin: "ager", german: "Acker, Feld, Gebiet"},
    {latin: "agere", german: "treiben, tun"},
    {latin: "amicus", german: "Freund"},
    {latin: "animus", german: "Geist, Gemüt"},
    {latin: "annus", german: "Jahr"},
    {latin: "arbitrari", german: "glauben, meinen"},
    {latin: "auctoritas", german: "Ansehen, Einfluss"},
    {latin: "audire", german: "hören"},
    {latin: "bellum", german: "Krieg"},
    {latin: "bonus", german: "gut"},
    {latin: "capere", german: "fassen, fangen, nehmen"},
    {latin: "castra", german: "Lager"},
    {latin: "causa", german: "Grund, Ursache, Prozess, Rechtsangelegenheit"},
    {latin: "cognoscere", german: "kennen lernen, erkennen, untersuchen"},
    {latin: "consilium", german: "Entschluss, Plan, Beratung"},
    {latin: "consul", german: "Konsul (oberster Beamter)"},
    {latin: "corpus", german: "Körper"},
    {latin: "credere", german: "glauben, meinen"},
    {latin: "dare", german: "geben"},
    {latin: "debere", german: "müssen, schulden, verdanken"},
    {latin: "deus", german: "Gott"},
    {latin: "dicere", german: "sagen"},
    {latin: "dies", german: "Tag, Termin"},
    {latin: "dignitas", german: "Würde"},
    {latin: "domus", german: "Haus"},
    {latin: "exercitus", german: "Heer"},
    {latin: "facere", german: "tun, machen"},
    {latin: "facilis", german: "leicht, bequem"},
    {latin: "ferre", german: "tragen, bringen, ertragen"},
    {latin: "fieri", german: "gemacht werden, werden, geschehen"},
    {latin: "fortuna", german: "Glück, Schicksal"},
    {latin: "genus", german: "Geschlecht, Art und Weise"},
    {latin: "gerere", german: "tragen, ausführen"},
    {latin: "gravis", german: "schwer, bedeutend, streng"},
    {latin: "habere", german: "haben, halten"},
    {latin: "homo", german: "Mensch, Mann"},
    {latin: "hostis", german: "Feind, Landesfeind"},
    {latin: "imperium", german: "Reich, Herrschaft, Befehl"},
    {latin: "intellegere", german: "verstehen, begreifen, merken"},
    {latin: "iubere", german: "jmd befehlen"},
    {latin: "iudex", german: "Richter, Richterin"},
    {latin: "iudicium", german: "Urteil"},
    {latin: "ius", german: "Recht"},
    {latin: "labor", german: "Arbeit"},
    {latin: "legatus", german: "Gesandter, Feldherr"},
    {latin: "lex", german: "Gesetz"},
    {latin: "litterae", german: "Brief, Literatur, Wissenschaft"},
    {latin: "locus", german: "Ort, Platz, Stelle"},
    {latin: "longus", german: "lang"},
    {latin: "magnus", german: "groß, bedeutend"},
    {latin: "manus", german: "Hand, Schar"},
    {latin: "mittere", german: "schicken, senden, werfen"},
    {latin: "modus", german: "Maß, Art, Weise"},
    {latin: "multi", german: "viele, zahlreiche"},
    {latin: "navis", german: "Schiff"},
    {latin: "nomen", german: "Name"},
    {latin: "novus", german: "neu"},
    {latin: "omnis", german: "jeder, ganz, Pl: alle"},
    {latin: "oppidum", german: "befestigte Siedlung, Stadt"},
    {latin: "pars", german: "Teil, Richtung, Seite"},
    {latin: "pater", german: "Vater"},
    {latin: "periculum", german: "Gefahr"},
    {latin: "petere", german: "erbitten, zu erreichen suchen, angreifen"},
    {latin: "populus", german: "Volk, Menge"},
    {latin: "posse", german: "können"},
    {latin: "provincia", german: "Amtsbereich, Provinz"},
    {latin: "publicus", german: "öffentlich, staatlich"},
    {latin: "putare", german: "meinen, glauben"},
    {latin: "relinquere", german: "verlassen, zurücklassen"},
    {latin: "res", german: "Sache, Ding"},
    {latin: "res publica", german: "Staat"},
    {latin: "rex", german: "König"},
    {latin: "scire", german: "wissen"},
    {latin: "scribere", german: "schreiben"},
    {latin: "senatus", german: "Senat"},
    {latin: "senectus", german: "das hohe Alter"},
    {latin: "senex", german: "alter Mann, Greis"},
    {latin: "signum", german: "Zeichen"},
    {latin: "socius", german: "Gefährte"},
    {latin: "solere", german: "gewohnt sein"},
    {latin: "studium", german: "Bemühung, Streben, Interesse"},
    {latin: "summus", german: "höchster, oberster"},
    {latin: "tempus", german: "Zeit"},
    {latin: "tenere", german: "(fest-)halten"},
    {latin: "terra", german: "Erde, Land"},
    {latin: "tollere", german: "(auf)heben, erheben, beseitigen"},
    {latin: "totus", german: "ganz"},
    {latin: "urbs", german: "Stadt, Hauptstadt"},
    {latin: "uti", german: "benutzen, gebrauchen"},
    {latin: "velle", german: "wollen"},
    {latin: "venire", german: "kommen"},
    {latin: "videre", german: "sehen"},
    {latin: "vir", german: "Mann"},
    {latin: "virtus", german: "Tapferkeit, Tatkraft, Tugend"},
    {latin: "vis", german: "Kraft, Gewalt, Stärke"},
    {latin: "vita", german: "Leben"},
    {latin: "vivere", german: "leben"}
];
